version: '2'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  webapi:
    container_name: webapi
    build:
      context: ../dotnet-express-mapper
    restart: always
    environment:
      MONGO_HOST: mongo
    ports:
      - 5000:80
    depends_on:
      - mongo