version: '3.4'

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    # volumes:
    #   - datatest1:/var/opt/mssql

  basket.data:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: admin

  identity.api:
    container_name: identity.api
    build:
      context: .
      dockerfile: src/Identity/Dockerfile
    depends_on:
      - sql.data
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: Server=sql.data;Database=IdentityDb;User Id=sa;Password=Your_password123
      BasketApiClient: http://localhost:6002
      MvcClient: http://localhost:6004
    ports:
      - "6001:80"

  basket.api:
    container_name: basket.api
    build:
      context: .
      dockerfile: src/Basket.API/BasketAPI/Dockerfile
    depends_on:
      - basket.data
      - rabbitmq
      - identity.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      IdentityUrl: http://identity.api
      IdentityUrlExternal: http://localhost:6001
      ConnectionString: basket.data
      EventBusConnection: rabbitmq
      EventBusUserName: admin
      EventBusPassword: password
    ports:
      - "6002:80"

  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
    ports:
      - "6003:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: Server=sql.data;Database=CatalogDb;User Id=sa;Password=Your_password123
      EventBusConnection: rabbitmq
      EventBusUserName: admin
      EventBusPassword: password
      AzureStorageEnabled: "false"

  mapusermvc:
    container_name: mapusermvc
    build:
      context: .
      dockerfile: src/MapUserMVC/Dockerfile
    ports:
      - "6004:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      # Using Local Mac
      IdentityUrl: http://docker.for.mac.localhost:6001

  # webmvc:
  #   container_name: webmvc
  #   build:
  #     context: .
  #     dockerfile: src/WebMVC/Dockerfile
  #   ports:
  #     - "6004:80"
  #   depends_on:
  #     - basket.data
  #     - rabbitmq
  #     - identity.api
  #   environment:
  #     useLoadTest: "false"
  #     ASPNETCORE_ENVIRONMENT: Development
  #     ASPNETCORE_URLS: http://0.0.0.0:80
  #     IdentityUrl: http://localhost:6001
  #     IdentityUrlExternal: http://localhost:6001
  #     CallBackUrl: http://localhost:6001
  #     PurchaseUrl: http://localhost:6003

volumes:
  datatest1: