version: '3.4'

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    # volumes:
    #   - data:/var/opt/mssql

  basket.data:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: admin

  identity.api:
    container_name: identity.api
    build:
      context: .
      dockerfile: src/Identity/Dockerfile
    depends_on:
      - sql.data
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: Server=sql.data;Database=IdentityDb;User Id=sa;Password=Your_password123
      BasketApiClient: http://localhost:6002
      MapUserMvcClient: http://localhost:6004
      MvcClient: http://localhost:6007
      WebhooksWebClient: http://localhost:6005
      WebhooksApiClient: http://localhost:6006
      WebShoppingAggClient: http://localhost:6008
      OrderingApiClient: http://localhost:6011
    ports:
      - "6001:80"

  basket.api:
    container_name: basket.api
    hostname: basket.api
    build:
      context: .
      dockerfile: src/Basket.API/BasketAPI/Dockerfile
    depends_on:
      - basket.data
      - rabbitmq
      - identity.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      IdentityUrl: http://identity.api
      IdentityUrlExternal: http://localhost:6001
      ConnectionString: basket.data
      EventBusConnection: rabbitmq
      EventBusUserName: admin
      EventBusPassword: password
    ports:
      - "6002:80"

  catalog.api:
    container_name: catalog.api
    hostname: catalog.api
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
    ports:
      - "6003:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: Server=sql.data;Database=CatalogDb;User Id=sa;Password=Your_password123
      EventBusConnection: rabbitmq
      EventBusUserName: admin
      EventBusPassword: password
      AzureStorageEnabled: "false"

  # mapusermvc:
  #   container_name: mapusermvc
  #   build:
  #     context: .
  #     dockerfile: src/MapUserMVC/Dockerfile
  #   ports:
  #     - "6004:80"
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: Development
  #     ASPNETCORE_URLS: http://0.0.0.0:80
  #     # Using Local Mac
  #     IdentityUrl: http://docker.for.mac.localhost:6001

  webhook.client:
    container_name: webhook.client
    build:
      context: .
      dockerfile: src/WebhookClient/Dockerfile
    ports:
      - "6005:80"
    depends_on:
      - webhooks.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      IdentityUrl: http://docker.for.mac.localhost:6001
      IdentityUrlExternal: http://localhost:6001
      CallBackUrl: http://localhost:6005
      SelfUrl: http://localhost:6005
      # Webhooks are registered with this token (any value is valid) but the client won't check it
      Token: 6168DB8D-DC58-4094-AF24-483278923590
      WebhooksUrl: http://webhooks.api

  webhooks.api:
    container_name: webhooks.api
    build:
      context: .
      dockerfile: src/Webhooks.API/Dockerfile
    ports:
      - "6006:80"
    depends_on:
      - sql.data
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      # IdentityUrl: http://docker.for.mac.localhost:6001
      IdentityUrl: http://identity.api
      IdentityUrlExternal: http://localhost:6001
      ConnectionString: Server=sql.data;Database=WebhooksDb;User Id=sa;Password=Your_password123
      EventBusConnection: rabbitmq
      EventBusUserName: admin
      EventBusPassword: password

  webshoppingagg:
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Shopping/aggregator/Dockerfile
    depends_on:
      - identity.api
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "6008:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      urls__basket: http://basket.api
      urls__catalog: http://catalog.api
      urls__identity: http://identity.api
      IdentityUrlExternal: http://localhost:6001

  webapigw:
    container_name: web.apigw
    build:
      context: .
      dockerfile: src/ApiGateways/ApiGw-Base/Dockerfile
    depends_on:
      - identity.api
      - catalog.api
      - basket.api
    links:
      - identity.api
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "6009:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      # Local: You need to open your local dev-machine firewall at range 5100-5110.
      IdentityUrl: http://identity.api
    volumes:
      - "./src/ApiGateways/apigw-config/configuration.json:/app/configuration.json"

  webmvc:
    container_name: webmvc
    build:
      context: .
      dockerfile: src/WebMVC/Dockerfile
    ports:
      - "6007:80"
    depends_on:
      - basket.data
      - rabbitmq
      - identity.api
    environment:
      UseCustomizationData: "True"
      useLoadTest: "false"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      IdentityUrl: http://docker.for.mac.localhost:6001
      IdentityUrlExternal: http://localhost:6001
      CallBackUrl: http://localhost:6007
      PurchaseUrl: http://webapigw
      EventBusConnection: rabbitmq
      EventBusUserName: admin
      EventBusPassword: password

  ordering.api:
    container_name: ordering.api
    build:
      context: .
      dockerfile: src/Ordering/Ordering.API/Dockerfile
    ports:
      - "6011:80"
    depends_on:
      - basket.data
      - rabbitmq
      - identity.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:80
      ConnectionString: Server=sql.data;Database=OrderingDb;User Id=sa;Password=Your_password123
      IdentityUrl: http://docker.for.mac.localhost:6001
      IdentityUrlExternal: http://localhost:6001
      CallBackUrl: http://localhost:6007
      PurchaseUrl: http://webapigw
      UseLoadTest: "False"
volumes:
  data: