
apiVersion: v1
kind: ConfigMap
metadata:
  name: externalcfg
data:
  ConnectionString: Server=sql-data;Initial Catalog=master;User Id=sa;Password=Your_password123;
  UseAzureSignalR: "False"
  Azure__SignalR__ConnectionString: ""