apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: basket
  name: basket
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: basket
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basket
spec:
  template:
    metadata:
      labels:
        app: eshop
        component: basket
    spec:
      containers:
      - name: basket
        image: nhatthai/dotnet-basket.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /basket-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
              name: externalcfg
              key: basket__ConnectionString
        - name: EventBusConnection
          valueFrom:
            configMapKeyRef:
              name: externalcfg
              key: all__EventBusConnection
        - name: EventBusUserName
          valueFrom:
            configMapKeyRef:
              name: externalcfg
              key: all__EventBusUserName
        - name: EventBusPassword
          valueFrom:
            configMapKeyRef:
              name: externalcfg
              key: all__EventBusPassword
        - name: AzureServiceBusEnabled
          valueFrom:
            configMapKeyRef:
              name: externalcfg
              key: all__UseAzureServiceBus
        - name: OrchestratorType
          value: 'K8S'
        ports:
        - containerPort: 80
