
apiVersion: v1
kind: ConfigMap
metadata:
  name: externalcfg
  labels:
    app: eshop
data:
# Basket.API entries
  basket__ConnectionString: REDIS CONNECTION STRING FOR BASKET
# Catalog.API entries
  catalog__ConnectionString: Catalog SQL SERVER CONNECTION STRING (Server=xxxx;Intial Catalog=yyy;....)
# Global entries
  all_UseAzureServiceBus: "TRUE"
  keystore: REDIS CONNECTION STRING FOR KEYSTORE
  all_EventBusConnection: CONNECTION_STRING (NAME OF RABBITMQ CONTAINER OR Endpoint=sb://XXXX in case of using Azure)