
apiVersion: v1
kind: ConfigMap
metadata:
  name: externalcfg
  labels:
    app: eshop
data:
# Basket.API entries
  basket__ConnectionString: basket-data
# Catalog.API entries
  catalog__ConnectionString: Server=sql-data;Initial Catalog=catalogdb;User Id=sa;Password=Your_password123;
# Global entries
  all__EventBusConnection: Endpoint=sb://[instance-name].servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=[your-access-key];EntityPath=eshop_event_bus
  all__UseAzureServiceBus: "TRUE"
  all__AppInsightsInstrumentKey: "[App-Insights-Key]"
  all__AzureBlobStorageConnection: DefaultEndpointsProtocol=https;AccountName=[storage-name];AccountKey=[KEY];EndpointSuffix=core.windows.net