apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: eshop
    component: frontend
  name: eshop-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /rabbitmq
        backend:
          serviceName: rabbitmq
          servicePort: 15672
      - path: /basket-api
        backend:
          serviceName: basket
          servicePort: 80
      - path: /catalog-api
        backend:
          serviceName: catalog
          servicePort: 80
      - path: /identity
        backend:
          serviceName: catalog
          servicePort: 80