---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: eshop
    component: frontend
  name: eshop-ingress
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/ingress.class: addon-http-application-routing
    kubernetes.io/ingress.class: azure/application-gateway
    # nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: service.e37d5753bce448ad9b99.southeastasia.aksapp.io
    http:
      paths:
      - path: /basket-api
        backend:
          serviceName: basket
          servicePort: 80
      - path: /catalog-api
        backend:
          serviceName: catalog
          servicePort: 80