kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-load-balancer-conf
  namespace: kube-system
  labels:
    k8s-app: nginx-ingress-controller
data:
  hsts: "false"
  map-hash-bucket-size: "128"
  proxy-buffer-size: "128k"
  proxy-busy-buffers-size: "256k"