apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: webshoppingagg
  name: webshoppingagg
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: webshoppingagg
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webshoppingagg
spec:
  template:
    metadata:
      labels:
        app: eshop
        component: webshoppingagg
    spec:
      containers:
      - name: webshoppingagg
        image: nhatthai/dotnet-webshoppingagg
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /webshoppingagg
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: urls__basket
          valueFrom:
            configMapKeyRef:
              name: internalurls
              key: basket
        - name: urls__catalog
          valueFrom:
            configMapKeyRef:
              name: internalurls
              key: catalog
        - name: urls__identity
          valueFrom:
            configMapKeyRef:
              name: internalurls
              key: identity
        - name: urls__orders
          valueFrom:
            configMapKeyRef:
              name: internalurls
              key: orders
        - name: IdentityUrl
          valueFrom:
            configMapKeyRef:
              name: urls
              key: IdentityUrl
        - name: IdentityUrlExternal
          valueFrom:
            configMapKeyRef:
              name: urls
              key: IdentityUrlExternal
        ports:
        - containerPort: 80
