version: '2'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  webapi:
    container_name: webapi
    build:
      context: ../jwt-authentication-api
    ports:
      - "5000:80"
    environment:
      ConnectionString: mongodb://root:example@mongo:27017
    depends_on:
      - mongo